### ISSUE TITLE
Sorting writer is not able to create multiple row groups

### ISSUE THREAD

**Issue by anups4** [parquet-go/parquet-go#98] opened 2023-11-29 02:29 UTC
I am trying to control number of rows written per row group in an output file but it does not seem to work. Input file has >570000 records. Not sure if I am missing anything in below code. Can someone help please? 

```
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/parquet-go/parquet-go"
)

func main() {
	file1 := "large_file.parquet"
	file2 := "large_file_control_row_group.parquet"
	f1, err := os.Open(file1)
	if err != nil {
		panic(err)
	}
	defer f1.Close()

	s1, err := os.Stat(file1)
	if err != nil {
		panic(err)
	}

	p1, err := parquet.OpenFile(f1, s1.Size())
	if err != nil {
		panic(err)
	}
	if size := p1.Size(); size != s1.Size() {
		fmt.Errorf("file size mismatch: want=%d got=%d", s1.Size(), size)
		panic(err)
	}
	schema := p1.Schema()
	fmt.Println("file1 schema: ", schema)
	fmt.Println("file1 gotype", schema.GoType())

	reader := parquet.NewGenericReader[any](f1, &parquet.ReaderConfig{
		Schema: schema,
	})
	numRows := reader.NumRows()
	out := make([]parquet.Row, 0)
	for _, rowgroup := range p1.RowGroups() {
		out1 := make([]parquet.Row, rowgroup.NumRows())
		_, err := reader.ReadRows(out1)
		if err != nil {
			panic(err)
		}
		out = append(out, out1...)
	}
	fmt.Println("file1 numRows", numRows)
	fmt.Println("file1 out= ", len(out))
	fmt.Println("file1 out= ", reflect.TypeOf(out[0]))

	f2, err := os.Create(file2)
	if err != nil {
		panic(err)
	}
	defer f2.Close()

	pw := parquet.NewSortingWriter[any](f2, int64(50000),
		&parquet.WriterConfig{
			//	PageBufferSize: 2560,
			Schema:      schema,
			Compression: &parquet.Zstd,
		})
	n, err := pw.WriteRows(out)
	if err != nil {
		panic( fmt.Sprintf("failed to write parquet file  err: ", file2, err))
	}
	fmt.Println("written rows to parquet file : ", n, file2)
	if err := pw.Close(); err != nil {
		panic( fmt.Sprintf("failed to close parquet file, err:", file2, err))
	}
	fmt.Println("closed parquet file", file2)
}
```

**Comment by fpetkovski** [comment] 2023-11-29 05:30
Thanks for reporting this @anups4, I believe it might be a duplicate of https://github.com/parquet-go/parquet-go/issues/82.

**Closed** 2023-12-04 16:10 UTC

**Comment by mustafa-qamaruddin** [comment] 2024-05-15 09:51
I have a similar issue, the generated file using SortingWriter contains only one rowgroup, regardless of the configurations. Here is the code to reproduce the bug:


```go
package main

import (
	"github.com/google/uuid"
	"github.com/parquet-go/parquet-go"
	"log"
	"math"
	"math/rand"
	"os"
)

// DummyStruct is a dummy struct to replace LineItemPartitionedDataModel
type DummyStruct struct {
	Field1 string
	Field2 int
	Field3 float64
}

func openDummyParquetPartitionedFile(filePath string, buffDir string) *parquet.SortingWriter[DummyStruct] {
	output, err := os.Create(filePath)
	if err != nil {
		log.Fatalf("Failed to create file: %v", err)
	}

	writer := parquet.NewSortingWriter[DummyStruct](output, 1e6,
		parquet.ColumnPageBuffers(
			parquet.NewFileBufferPool(buffDir, "cp-buffers.*"),
		),
		parquet.Compression(&parquet.Zstd),
		parquet.MaxRowsPerRowGroup(1e4),
		parquet.SortingWriterConfig(
			parquet.SortingColumns(
				parquet.Ascending("Field1"),
				parquet.Ascending("Field2"),
			),
			parquet.SortingBuffers(
				parquet.NewFileBufferPool(buffDir, "sw-buffers.*"),
			),
		),
	)
	if err != nil {
		log.Fatalf("Failed to create parquet writer: %v", err)
	}

	return writer
}

func writeDummyParquetPartitionedFile(buffer *parquet.SortingWriter[DummyStruct], dummyData []DummyStruct) {
	if _, err := buffer.Write(dummyData); err != nil {
		log.Fatalf("Failed to write to parquet: %v", err)
	}
}

func closeDummyParquetPartitionedFile(writer *parquet.SortingWriter[DummyStruct]) {
	if err := writer.Close(); err != nil {
		log.Fatalf("Failed to close parquet writer: %v", err)
	}
}

func verifyRowGroups(filepath string) {
	b, err := os.Open(filepath)
	if err != nil {
		log.Fatalf("Could not open file: %v", err)
	}
	defer b.Close()

	// Get file size
	fi, err := b.Stat()
	if err != nil {
		log.Fatalf("Could not obtain file stats: %v", err)
	}

	var f *parquet.File
	f, err = parquet.OpenFile(b, fi.Size())
	if err != nil {
		log.Fatalf("Failed to open file: %v", err)
	}

	log.Printf("# RowGroups: %d\n", len(f.RowGroups()))

	for i, rowGroup := range f.RowGroups() {
		println("RowGroup:", i, ", NumRows:", rowGroup.NumRows(), ", SortingColumns: ", len(rowGroup.SortingColumns()))
	}
}

func main() {
	// Open a parquet file
	writer := openDummyParquetPartitionedFile("dummy.parquet", "/tmp")

	// Create some dummy data
	dummyData := make([]DummyStruct, 0)
	for i := 0; i < 1e6; i++ {
		xuuid, _ := uuid.NewUUID()
		dummyData = append(dummyData, DummyStruct{
			Field1: xuuid.String(),
			Field2: rand.Int(),
			Field3: rand.Float64(),
		})

		if math.Mod(float64(i), 1e3) == 0 {
			// Write the dummy data to the parquet file
			writeDummyParquetPartitionedFile(writer, dummyData)
			log.Printf("I:[%d], \tSz:[%d]\n", i+1, len(dummyData))
			dummyData = make([]DummyStruct, 0)
		}
	}

	// Close the file
	closeDummyParquetPartitionedFile(writer)
	// Verify Number of Row Groups
	verifyRowGroups("dummy.parquet")
	// Cleanup
	os.RemoveAll("/tmp")
	os.RemoveAll("dummy.parquet")
}
```
